#!/bin/zsh
set -e

. /usr/lib/iserv/cfg


for domain in ${MailTreatAsLocal[@]}
do
  MailOrgDomains+=("$domain")
done

CFG_STR='('

for domain in ${MailOrgDomains[@]}
do
  CFG_STR+="\"$domain\" "
done

CFG_STR="${CFG_STR: : -1}"
CFG_STR+=')'

# quote all except letters and digits
CFG_STR="$(echo "$CFG_STR" | sed 's/\([^A-Za-z0-9]\)/\\\1/g')"

sed -i "s/^MailOrgDomains *=.*\$/MailOrgDomains=$STR/" /etc/iserv/config
sed -i "s/^MailTreatAsLocal *=.*\$/MailTreatAsLocal=()/" /etc/iserv/config
